schemaVersion: 1
sessionDefaults:
  projectPath: /Users/tangyuxuan/Desktop/Claude/HOLO/Holo/Holo APP/Holo/Holo.xcodeproj
  scheme: Holo
  simulatorName: iPhone 17
  simulatorId: F9F5EDDE-EB22-4951-A876-532BC5C53687
  simulatorPlatform: iOS Simulator
